[project]
name = "In-Class_Programming--Vega-Altair"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altair[all]>=6.0.0",
    "marimo>=0.19.1",
    "nbformat>=5.10.4",
    "pandas>=2.3.3",
    "vega-datasets>=0.9.0",
    "wheel>=0.45.1",
]
